# Generated by Django 5.2.8 on 2025-11-19 18:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('units', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('dataset_slug', models.CharField(help_text='Slug used in Met Office dataset URLs', max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClimateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('period_type', models.CharField(choices=[('month', 'Month'), ('season', 'Season'), ('annual', 'Annual')], max_length=12)),
                ('period', models.CharField(help_text="Month short name, season code (win/spr/sum/aut) or 'ann'", max_length=12)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('source_last_updated', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='weather.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='weather.region')),
            ],
            options={
                'ordering': ['parameter', 'region', 'year', 'period'],
                'unique_together': {('region', 'parameter', 'year', 'period_type', 'period')},
            },
        ),
    ]
